version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8001:8000"
    environment:
      DEBUG: "True"
    volumes:
      - .:/clothing_store
