version: '3.3'

services:
  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"

nginx:
  image: nginx:1.18.0 (Ubuntu)
  depends_on:
    - django
  ports:
    - "80:80"
